/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.7 */

#ifndef PB_W3BSTREAM_PB_H_INCLUDED
#define PB_W3BSTREAM_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _Header {
    pb_callback_t event_type; /* event type */
    pb_callback_t pub_id; /* the unique identifier for publisher */
    pb_callback_t token; /* for validation message */
    int64_t pub_time; /* event pub timestamp */
    pb_callback_t event_id; /* event id for tracing */
} Header;

typedef struct _Event {
    bool has_header;
    Header header;
    pb_callback_t payload;
} Event;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define Header_init_default                      {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, 0, {{NULL}, NULL}}
#define Event_init_default                       {false, Header_init_default, {{NULL}, NULL}}
#define Header_init_zero                         {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, 0, {{NULL}, NULL}}
#define Event_init_zero                          {false, Header_init_zero, {{NULL}, NULL}}

/* Field tags (for use in manual encoding/decoding) */
#define Header_event_type_tag                    1
#define Header_pub_id_tag                        2
#define Header_token_tag                         3
#define Header_pub_time_tag                      4
#define Header_event_id_tag                      5
#define Event_header_tag                         1
#define Event_payload_tag                        2

/* Struct field encoding specification for nanopb */
#define Header_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   event_type,        1) \
X(a, CALLBACK, SINGULAR, STRING,   pub_id,            2) \
X(a, CALLBACK, SINGULAR, STRING,   token,             3) \
X(a, STATIC,   SINGULAR, INT64,    pub_time,          4) \
X(a, CALLBACK, SINGULAR, STRING,   event_id,          5)
#define Header_CALLBACK pb_default_field_callback
#define Header_DEFAULT NULL

#define Event_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  header,            1) \
X(a, CALLBACK, SINGULAR, BYTES,    payload,           2)
#define Event_CALLBACK pb_default_field_callback
#define Event_DEFAULT NULL
#define Event_header_MSGTYPE Header

extern const pb_msgdesc_t Header_msg;
extern const pb_msgdesc_t Event_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define Header_fields &Header_msg
#define Event_fields &Event_msg

/* Maximum encoded size of messages (where known) */
/* Header_size depends on runtime parameters */
/* Event_size depends on runtime parameters */

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
